### ISSUE TITLE
Updated documentation removes all Not Performed data points?

### ISSUE THREAD

**Issue by joshua-hiltunen** [drajer-health/uds-plus#18]
I noticed this when the documentation moved from github to https://fhir.org/guides/hrsa/uds-plus/ and wanted to confirm the accuracy and implications.

In previously published versions of the UDS+ IG, there were many instances of negative documentation (Not Performed) that were required.  Those are no longer present in the currently published version of the documentation.  Does the removal of the elements indicate that the data is no longer required to meet current reporting requirements?  Or is this something that was removed from the documentation, but presumed as provided regardless (simplification of documentation by omission vs simplification of data model by removal)?

As an example, the 0.2.0 version of the documentation indicated:
![image](https://github.com/drajer-health/uds-plus/assets/113625306/34b67f8e-d13f-4079-9a2e-ccb0d2b8c416)

**Comment by ljtucker** [comment]
Hi @joshua-hiltunen, this was a simplification of the mapping table. In the current iteration of the IG, we have moved these terms INSIDE the relevant resourse structure definitions, rather than have them in the mapping table. Here are a few examples:

- [De-Identified UDS Plus ServiceRequest](https://fhir.org/guides/hrsa/uds-plus/StructureDefinition-uds-plus-servicerequest.html) (ServiceRequest donotperform)
- [De-Identified UDS Plus Procedure](https://fhir.org/guides/hrsa/uds-plus/StructureDefinition-uds-plus-procedure.html) (Procedure ProcedureNotPerformedReason)

**Comment by nbashyam** [comment]
When the mapping table does not mention the data elements it is not required for meeting the measure calculations for that specific measure.

**Comment by joshua-hiltunen** [comment]
That sounds great!  Just to be clear, if DoNotPerformReason is something that one of our EHRs does not support today for an element used in the measures (Observation, for example), and that is not indicated on the dataelements page, it won't be an issue for us moving forward with participation in Synthetic Testing or for our customer's submissions?
