### ISSUE TITLE
Inferno Test Kit $import operation returns HTML without Content-Location

### ISSUE THREAD

**Issue by cooperthompson** [drajer-health/uds-plus#58]
This is a cross-post from the Inferno [UDS Plus Test Kit issue](https://github.com/inferno-framework/uds-plus-test-kit/issues/23), but to keep all the UDS+ issues in one spot:  the Inferno Test Kit is returning an HTML page without a Content-Location header in response to the $import operation call.

**Comment by ljtucker** [comment]
The POST tests in the UDS+ Inferno Test Kit (e.g., Receive UDS+ Import Manifest via POST request, which is one of our first requests when a UDS+ Volunteer Tester is practicing connectivity) are only acting as a rudimentary data receiver compared to the UDS+ Sandbox (which actually tests against an endpoint (valid conformant server/s). These tests are not a valid test of the FHIR submission process, but an initial practice run to see if your synthetic test data is healthy and likely ready for submitting to the UDS+ sandbox. If you are looking for a JSON response instead of HTML, then we advise obtaining access to the UDS+ sandbox.
