### ISSUE TITLE
Adverse Event Category should not be required

### ISSUE THREAD

**Issue by sginsbur** [drajer-health/uds-plus#6]
For [UDS Plus Adverse Event](https://fhir.org/guides/hrsa/uds-plus/StructureDefinition-uds-plus-adverseevent.html), the Category element has a cardinality of 0..*, which means indicates any number of categories can be sent, including 0.
This is somewhat contradictory to the Must Send flag on this element.

In Epic, you there is no way to discretely document an Adverse Event Category and the cardinality reflects that it will not make sense to send in some instances. We request that you remove the Must Send flag from the Adverse Event element.

**Comment by cooperthompson** [comment]
0...* means it is optional on a given instance.

MS means you have to support it on at least once instance.

So 0..* MS is a fine combination, which ultimately means that the data is optional (and may never be populated) when submitting to UDS+, but the developer of the system that is doing the submission must have the capability to send it.


So in summary, a  0..* MS element means that UDS+ isn't requiring the element as part of any submission but the data should be sent if it exists.


We can just send "none" as the category, since the UDS+ profile does not have a binding to a value set.  The list of values in the spec are just part of the short display property, which isn't a value set with a binding.

**Comment by cooperthompson** [comment]
This might be a good option:

 <category>  
    <coding>  
      <system value="http://terminology.hl7.org/CodeSystem/data-absent-reason"/>  
      <code value="unsupported"/>  
      <display value="Unsupported"/>  
    </coding>  
  </category>

**Comment by nbashyam** [comment]
Thanks Cooper. Closing this issue without any further changes.
