### ISSUE TITLE
Should the partial submission and related flags be "must-support"?

### ISSUE THREAD

**Issue by cooperthompson** [drajer-health/uds-plus#67]
The UDS+ Must Support definition includes this:

`Systems SHALL be capable of populating data elements as specified by the profiles and data elements are returned using the specified APIs in the capability statement.
`

It seems like some systems may not need to support partial submissions.  So do those parameters need to be marked as MS in the manifest?  https://fhir.org/guides/hrsa/uds-plus/StructureDefinition-uds-plus-import-manifest.html

Note that this is a low priority for me personally, since we _will_ need to support partial submissions, so this is really just an observation about the spec.

**Comment by nbashyam** [comment]
The reason we are thinking MUST SUPPORT is for everyone to move to 1.0.2 eventually and there may be a need for the EHR product to be used at a HC who may need the flag to be supported. This happens when HC's combine with others and become a bigger Health Center. So we will leave it as MUST SUPPORT.
